### ISSUE TITLE
make:command - Command with identifier xyz has not been registered

### ISSUE THREAD

**Issue by loeffe1** [b13/make#60]
I tried creating a schedulable command via `make:command`. I can run it manually without any issues, but running it via cron fails with a `Command with identifier vendor-package:import-publications has not been registered` error.

I am on TYPO3 11.5.41 using version 0.1.8 of b13/make.

The command added this to my Services.yaml:

```
  Vendor\Package\Command\ImportPublicationsCommand:
    tags:
      -
        name: console.command
        command: 'vendor-package:import-publications'
        description: 'Imports publications'
        schedulable: true
    calls:
      -
        method: injectRepositories
        arguments:
          $categoryRepository: '@Vendor\Package\Domain\Repository\CategoryRepository'
          $locationRepository: '@Vendor\Package\Domain\Repository\LocationRepository'
          $companyRepository: '@Vendor\Package\Domain\Repository\CompanyRepository'
```

and created an ImportPublicationsCommand class:

```
<?php

declare(strict_types=1);

namespace Vendor\Package\Command;

use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;

class ImportPublicationsCommand extends Command
{
    protected function configure(): void
    {
        $this->setDescription('Imports publications');
    }

    protected function execute(InputInterface $input, OutputInterface $output): int
    {
        // Do awesome stuff
        return 0;
    }
}
```
